name: auto-update

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [master]
  schedule:
    - cron:  '0 0 * * *'
permissions:
  contents: write
jobs:
  generate_rpg_list:
    name: Generate RPG List
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: sudo apt install -y curl jq
    - shell: bash
      env:
        steam_api_key: ${{ secrets.steam_api_key }}
      run: ./build-rpglist.sh "$steam_api_key"

    - name: Set date env
      run: echo "TODAY=$(date '+%Y/%m/%d')" >> $GITHUB_ENV
    
    - name: commit
      run: | 
	git config --global user.name "Github Action"
	git config --global user.email "xunpod@hotmail.com"
        git add .
        git commit -m "auto update" -a
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
    
    - name: Update Release
      uses: softprops/action-gh-release@v1
      with:
        files: rpglist-latest.json
        tag_name: latest
        name: ${{ env.TODAY }}
      env:
        GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
